[project]
name = "impl-html-parser-step-by-step"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=9.0.1",
]


[tool.pytest.ini_options]
python_files = ["test.py", "test_*.py", "*_test.py"]
